title: How to Create a Github Page
author: Ted Wang
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This page is about how to create a page with Github Page.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
